development:
  adapter: postgresql
  encoding: utf8
  database: visual_log_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: visual_log_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: visual_log_app
  pool: 5