development:
  adapter: mysql2
  encoding: utf8
  database: run_the_usa_development
  pool: 5
  user_name: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: run_the_usa_test
  pool: 5
  user_name: root
  password:
  socket: /tmp/mysql.sock